version : '2'

services:
        
    nginx:
        build: .
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - le_sslcerts:/etc/letsencrypt/

volumes:
    le_sslcerts:
        external: true
    
    