version : '2'

services:
        
    nginx:
        build: .
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - 301hub_sslcerts:/etc/letsencrypt/

volumes:
    301hub_sslcerts:
        external: true
    
    